### ISSUE TITLE
Write to log if height cannot be converted to inches correctly.

### ISSUE THREAD

**Issue by zo0o0ot** [Leagify/scrapysharp-dt2020#13]
Right now, the height conversion just takes in the height and converts to inches, or outputs 0 if it can't be converted.

https://github.com/Leagify/scrapysharp-dt2020/blob/e263d63468933cc2d59659bd6faf60bdb2e86e0a/Program.cs#L423

It might be nice to write to the log when a height can't be converted.  In that case, we may want to refactor convertHeightToInches to take two arguments, the height and the playerName, then write something like:

Player *playerName* height of *originalHeight* not converted properly, entering 0 instead.

to the log file, similar to this:

https://github.com/Leagify/scrapysharp-dt2020/blob/e263d63468933cc2d59659bd6faf60bdb2e86e0a/Program.cs#L259

**Comment by cgunston** [comment]
Hi Zo0o0ot

I would really like to help out on this but I'm still pretty new.

I can definitely make this happen but do you have a preference on what log file this would be written to?

Cheers
Callum

**Comment by zo0o0ot** [comment]
@cgunston You could put this in Mismatches.log

**Comment by JEvason90** [comment]
@zo0o0ot @cgunston I can also probably help with this. Having looked at the code there is also opportunity to refactor. Would a Logging Helper / Class be acceptable?

**Comment by zo0o0ot** [comment]
@JEvason90 I'm open to refactoring.

**Comment by cgunston** [comment]
Created https://github.com/Leagify/scrapysharp-dt2020/pull/15 for this issue. Please could you review.
