### ISSUE TITLE
Get Region from StatesToRegions.csv and join with LINQ

### ISSUE THREAD

**Issue by zo0o0ot** [Leagify/scrapysharp-dt2020#14]
There is a StatesToRegions.csv file in the info directory. There are two columns - state and region, both strings.
We should read in that file into a new mapped class, maybe called Regions.
It will look similar to this: 
https://github.com/Leagify/scrapysharp-dt2020/blob/8d98052cdbda5d74e54da00bcaa7b8fb1eb2043d/Program.cs#L119-L126

After we read in that csv into a list of Regions, we need to use LINQ to add a join to the region on 
school.state to equal region.state.
Once we have properly joined that information in LINQ, we can add Region = Regions.region or whatever we choose to call it to the anonymous type that we are creating. That should add an additional column to joinedRanks2020.csv when we write it out.

**Comment by Yikal** [comment]
I'll do that, if that's ok.

**Comment by zo0o0ot** [comment]
Fixed in #16
