### ISSUE TITLE
Add xUnit test project and first simple test

### ISSUE THREAD

**Issue by zo0o0ot** [Leagify/scrapysharp-dt2020#20]
Using xUnit, create the appropriate test directory and one simple test that returns true.

I'm thinking that using the CLI might be a good option.  Here's a Microsoft article about setting everything up:
https://docs.microsoft.com/en-us/dotnet/core/tutorials/testing-with-cli

**Comment by pjgeutjens** [comment]
I could pick this up for you

**Comment by GuilhermeMartins10** [comment]
Hi, I can do this

**Comment by zo0o0ot** [comment]
@GuilhermeMartins10  FYI, https://github.com/Leagify/scrapysharp-dt2020/pull/21 is in the process of being reviewed.
