### ISSUE TITLE
Move system out println statements to use log file instead

### ISSUE THREAD

**Issue by zo0o0ot** [Leagify/scrapysharp-dt2020#5]
This program is currently very "chatty" on the command line.
Changing these system out print statements to append to a log file, maybe in a logs directory, would be nice.
Different log levels would be nice, as there is certainly some verbose output that isn't always needed.

**Comment by allst896** [comment]
I can do this work for you.

**Comment by zo0o0ot** [comment]
@allst896 You've done some really good work here.  However, I've updated the .gitignore file, so some of the files in your PR no longer need to be added.  If possible, could you either fix your current PR or submit a new one?

**Comment by zo0o0ot** [comment]
Initial work for this was completed in #11 and everything was fixed up in #12. Good to go.
