### ISSUE TITLE
Update .gitignore file so that compiled output isn't tracked.

### ISSUE THREAD

**Issue by zo0o0ot** [Leagify/scrapysharp-dt2020#6]
I tried using a .gitignore file from www.gitignore.io to prevent this repository from tracking bin and obj files, but it doesn't seem to be working.  This is particularly troublesome when trying to work on this repo in Linux or on a Mac, because the output in those directories appears to be OS-specific.

It would be nice if this worked correctly, and the appropriate files were removed from being tracked.

**Comment by DevIvanVarela** [comment]
I've made some changes in .gitignore file, now, it ignores more folders and types of files.

**Comment by zo0o0ot** [comment]
Fixed in #10
